// ── theme.js ─────────────────────────────────────────────────────────────────
// The Collection treasure: a "world concert tour" (UX §4.2). Pure swappable data —
// emoji + name + a one-line fact, plus `costPoints`, a *cumulative* lifetime-points
// threshold at which the tile unlocks. Tiles are sorted ascending by costPoints
// (the first, "home", is free at 0).
//
// The full multi-year list: 76 tiles on a banded cost curve (UX §4.2 "Sizing"),
// cumulative thresholds from 0 to 100,000 points (~3 years of daily practice). The
// engine is count-agnostic, so growing or re-theming this list touches no code.

export const WORLD_TOUR = [
  // ── Band A (existing) ─────────────────────────────────────────────────────
  { id: "home",           emoji: "🏠", name: "Your practice room",       costPoints: 0,      fact: "Where every tour begins." },
  { id: "cremona",        emoji: "🎻", name: "Cremona",                  costPoints: 40,     fact: "Where Stradivari built his violins and cellos." },
  { id: "paris",          emoji: "🗼", name: "Paris",                    costPoints: 90,     fact: "Home of the Conservatoire de Paris." },
  { id: "vienna",         emoji: "🏛️", name: "Vienna",                   costPoints: 160,    fact: 'The Musikverein\'s "Golden Hall."' },
  { id: "milan",          emoji: "🎭", name: "Milan",                    costPoints: 250,    fact: "La Scala, the world's most famous opera house." },
  { id: "prague",         emoji: "🏰", name: "Prague",                   costPoints: 360,    fact: "Where Mozart premiered Don Giovanni." },
  { id: "newyork",        emoji: "🗽", name: "New York",                 costPoints: 500,    fact: "Carnegie Hall — how do you get there? practice." },
  { id: "sydney",         emoji: "🌉", name: "Sydney",                   costPoints: 680,    fact: "The Opera House on the harbour." },
  { id: "tokyo",          emoji: "🏯", name: "Tokyo",                    costPoints: 900,    fact: "Suntory Hall, a jewel box of sound." },

  // ── Band B (~12 tiles, ~1,150 → ~6,000) ──────────────────────────────────
  { id: "london",         emoji: "🎺", name: "London",                   costPoints: 1150,   fact: "Royal Albert Hall hosts the BBC Proms every summer." },
  { id: "salzburg",       emoji: "🎼", name: "Salzburg",                 costPoints: 1400,   fact: "Mozart was born here in 1756." },
  { id: "berlin",         emoji: "🏛️", name: "Berlin",                   costPoints: 1700,   fact: "The Berlin Philharmonie has a vineyard-style seating design." },
  { id: "amsterdam",      emoji: "🎻", name: "Amsterdam",                costPoints: 2050,   fact: "The Concertgebouw is famous for its near-perfect acoustics." },
  { id: "moscow",         emoji: "🎭", name: "Moscow",                   costPoints: 2450,   fact: "The Bolshoi Theatre opened in 1825." },
  { id: "buenos-aires",   emoji: "🏟️", name: "Buenos Aires",             costPoints: 2900,   fact: "Teatro Colón is one of the world's top five opera houses." },
  { id: "boston",         emoji: "🎹", name: "Boston",                   costPoints: 3400,   fact: "Boston Symphony Hall is modeled on the Leipzig Gewandhaus." },
  { id: "venice",         emoji: "🌉", name: "Venice",                   costPoints: 3950,   fact: "Vivaldi wrote The Four Seasons while teaching here." },
  { id: "leipzig",        emoji: "🎼", name: "Leipzig",                  costPoints: 4500,   fact: "Bach worked at St. Thomas Church here for 27 years." },
  { id: "rome",           emoji: "🏛️", name: "Rome",                     costPoints: 5050,   fact: "The Accademia Nazionale di Santa Cecilia dates to 1585." },
  { id: "seoul",          emoji: "🎻", name: "Seoul",                    costPoints: 5550,   fact: "Seoul Arts Center hosts the nation's top classical concerts." },
  { id: "shanghai",       emoji: "🎹", name: "Shanghai",                 costPoints: 6000,   fact: "Shanghai Symphony Orchestra is the oldest in Asia, founded 1879." },

  // ── Band C (~25 tiles, ~6,800 → ~30,000) ─────────────────────────────────
  { id: "hamburg",        emoji: "🏟️", name: "Hamburg",                  costPoints: 6800,   fact: "The Elbphilharmonie sits on a converted warehouse on the Elbe." },
  { id: "st-petersburg",  emoji: "🏰", name: "St. Petersburg",           costPoints: 7700,   fact: "The Mariinsky Theatre is home to a world-famous orchestra and ballet." },
  { id: "chicago",        emoji: "🎺", name: "Chicago",                  costPoints: 8700,   fact: "Orchestra Hall opened in 1904 and seats over 2,500." },
  { id: "lucerne",        emoji: "🌉", name: "Lucerne",                  costPoints: 9800,   fact: "Lucerne Festival attracts top soloists every summer." },
  { id: "barcelona",      emoji: "🎭", name: "Barcelona",                costPoints: 11000,  fact: "The Palau de la Música Catalana is a UNESCO World Heritage Site." },
  { id: "los-angeles",    emoji: "🎼", name: "Los Angeles",              costPoints: 12200,  fact: "Walt Disney Concert Hall was designed by Frank Gehry." },
  { id: "edinburgh",      emoji: "🏰", name: "Edinburgh",                costPoints: 13500,  fact: "The Edinburgh Festival is one of the world's largest arts festivals." },
  { id: "tanglewood",     emoji: "🌿", name: "Tanglewood",               costPoints: 14900,  fact: "Yo-Yo Ma performed his first solo recital at Tanglewood." },
  { id: "helsinki",       emoji: "🎻", name: "Helsinki",                 costPoints: 16400,  fact: "Sibelius wrote Finlandia while living near Helsinki." },
  { id: "budapest",       emoji: "🏛️", name: "Budapest",                 costPoints: 17900,  fact: "The Budapest Festival Orchestra is ranked among Europe's finest." },
  { id: "rio",            emoji: "🎷", name: "Rio de Janeiro",           costPoints: 19500,  fact: "The Theatro Municipal opened in 1909 and seats 2,357." },
  { id: "cape-town",      emoji: "🎼", name: "Cape Town",                costPoints: 21100,  fact: "Cape Town Opera is the largest opera company in Africa." },
  { id: "verbier",        emoji: "🏔️", name: "Verbier",                  costPoints: 22800,  fact: "Verbier Festival brings world-class soloists to the Swiss Alps." },
  { id: "reykjavik",      emoji: "🎹", name: "Reykjavík",               costPoints: 24500,  fact: "Harpa concert hall glitters on Reykjavík's waterfront." },
  { id: "warsaw",         emoji: "🎻", name: "Warsaw",                   costPoints: 26200,  fact: "The Chopin International Piano Competition is held here every five years." },
  { id: "cleveland",      emoji: "🏛️", name: "Cleveland",                costPoints: 27400,  fact: "Severance Hall is home to one of America's \"Big Five\" orchestras." },
  { id: "singapore",      emoji: "🎭", name: "Singapore",                costPoints: 28600,  fact: "Esplanade - Theatres on the Bay is nicknamed the Durian." },
  { id: "brussels",       emoji: "🎺", name: "Brussels",                 costPoints: 29400,  fact: "The Queen Elisabeth Competition has launched many great cellists." },
  { id: "zurich",         emoji: "🎼", name: "Zurich",                   costPoints: 30000,  fact: "Tonhalle Zurich reopened after renovation in 2021 to great acclaim." },
  { id: "florence",       emoji: "🏛️", name: "Florence",                 costPoints: 30700,  fact: "The Maggio Musicale Fiorentino is Italy's oldest music festival." },
  { id: "montreal",       emoji: "🎺", name: "Montréal",                 costPoints: 31300,  fact: "Salle Wilfrid-Pelletier seats 2,982 and hosts the Orchestre symphonique de Montréal." },

  // ── Band D (~30 tiles, ~31,800 → ~100,000) ────────────────────────────────
  { id: "lisbon",         emoji: "🌉", name: "Lisbon",                   costPoints: 32200,  fact: "Teatro Nacional de São Carlos is Portugal's historic opera house." },
  { id: "munich",         emoji: "🏛️", name: "Munich",                   costPoints: 34000,  fact: "The Bavarian State Opera is one of Europe's leading opera houses." },
  { id: "oslo",           emoji: "🎹", name: "Oslo",                     costPoints: 36200,  fact: "Edvard Grieg's music has been tied to Norwegian culture for over 150 years." },
  { id: "copenhagen",     emoji: "🎻", name: "Copenhagen",               costPoints: 38400,  fact: "DR Koncerthuset has four halls with cutting-edge acoustic design." },
  { id: "stockholm",      emoji: "🎭", name: "Stockholm",                costPoints: 40600,  fact: "The Nobel Prize Concert is held at Konserthuset every December." },
  { id: "madrid",         emoji: "🎷", name: "Madrid",                   costPoints: 42900,  fact: "Teatro Real is Spain's main opera house, dating to 1850." },
  { id: "dubrovnik",      emoji: "🏰", name: "Dubrovnik",                costPoints: 45200,  fact: "The Dubrovnik Summer Festival has been held since 1950." },
  { id: "dresden",        emoji: "🏛️", name: "Dresden",                  costPoints: 47500,  fact: "The Semperoper premiered operas by Wagner and Richard Strauss." },
  { id: "toronto",        emoji: "🎼", name: "Toronto",                  costPoints: 49800,  fact: "Roy Thomson Hall is home to the Toronto Symphony Orchestra." },
  { id: "san-francisco",  emoji: "🌉", name: "San Francisco",            costPoints: 52200,  fact: "Davies Symphony Hall opened in 1980 on Van Ness Avenue." },
  { id: "philadelphia",   emoji: "🎻", name: "Philadelphia",             costPoints: 54600,  fact: "The Philadelphia Orchestra was the first American orchestra to tour China." },
  { id: "mexico-city",    emoji: "🏛️", name: "Mexico City",              costPoints: 57000,  fact: "Palacio de Bellas Artes has a famous Tiffany glass curtain on its stage." },
  { id: "athens",         emoji: "🏺", name: "Athens",                   costPoints: 59500,  fact: "The Odeon of Herodes Atticus, built in 161 AD, still hosts concerts." },
  { id: "istanbul",       emoji: "🕌", name: "Istanbul",                 costPoints: 62000,  fact: "Istanbul hosts one of Turkey's largest international music festivals." },
  { id: "beijing",        emoji: "🏯", name: "Beijing",                  costPoints: 64500,  fact: "The National Centre for the Performing Arts is called the Giant Egg." },
  { id: "nairobi",        emoji: "🎼", name: "Nairobi",                  costPoints: 67000,  fact: "The Kenya National Theatre has promoted African music and arts since 1952." },
  { id: "mumbai",         emoji: "🎭", name: "Mumbai",                   costPoints: 69500,  fact: "The NCPA in Mumbai is India's largest arts complex." },
  { id: "zagreb",         emoji: "🎻", name: "Zagreb",                   costPoints: 72000,  fact: "The Zagreb Philharmonic is one of the oldest orchestras in southeast Europe." },
  { id: "vilnius",        emoji: "🎼", name: "Vilnius",                  costPoints: 73300,  fact: "Vilnius hosts the Christopher Summer Festival of classical music every year." },
  { id: "aspen",          emoji: "🏔️", name: "Aspen",                    costPoints: 74600,  fact: "Aspen Music Festival has trained young musicians since 1949." },
  { id: "montevideo",     emoji: "🎹", name: "Montevideo",               costPoints: 77200,  fact: "Teatro Solís in Montevideo is one of South America's oldest opera houses." },
  { id: "melbourne",      emoji: "🎺", name: "Melbourne",                costPoints: 79800,  fact: "Hamer Hall sits on the Yarra River and seats over 2,600." },
  { id: "lyon",           emoji: "🎹", name: "Lyon",                     costPoints: 81100,  fact: "Opéra de Lyon is celebrated across Europe for adventurous programming." },
  { id: "auckland",       emoji: "🌏", name: "Auckland",                 costPoints: 82400,  fact: "Auckland Philharmonia is a leading New Zealand professional orchestra." },
  { id: "riga",           emoji: "🎭", name: "Riga",                     costPoints: 83700,  fact: "Latvian National Opera opened in 1919 and is a Baltic landmark." },
  { id: "taipei",         emoji: "🏯", name: "Taipei",                   costPoints: 85000,  fact: "National Concert Hall Taipei opened in 1987 in a classical Chinese building." },
  { id: "bogota",         emoji: "🎷", name: "Bogotá",                   costPoints: 86300,  fact: "Teatro Mayor Julio Mario Santo Domingo opened in 2008 and seats 1,800." },
  { id: "dubai",          emoji: "🕌", name: "Dubai",                    costPoints: 87600,  fact: "Dubai Opera opened in 2016 shaped like a traditional dhow boat." },
  { id: "baku",           emoji: "🎼", name: "Baku",                     costPoints: 90200,  fact: "Heydar Aliyev Center hosts concerts in a wave-shaped Zaha Hadid building." },
  { id: "lima",           emoji: "🎭", name: "Lima",                     costPoints: 92800,  fact: "Gran Teatro Nacional de Peru opened in 2012 and seats 1,500." },
  { id: "kyoto",          emoji: "⛩️",  name: "Kyoto",                    costPoints: 95400,  fact: "Kyoto Concert Hall is famous for its warm wooden interior." },
  { id: "wigmore",        emoji: "🎻", name: "Wigmore Hall",             costPoints: 97500,  fact: "Wigmore Hall in London is considered the world's top chamber music venue." },
  { id: "palais-garnier", emoji: "🎭", name: "Palais Garnier",           costPoints: 99000,  fact: "Paris's grand opera house inspired Gaston Leroux to write The Phantom of the Opera." },
  { id: "world-stage",    emoji: "🌍", name: "The World Stage",          costPoints: 100000, fact: "You have practiced your way to every corner of the musical world!" },
];
